all:
	mkdir -p ~/.icons ~/.themes
	ln -fs `realpath ./numix-icon-theme/Numix` ~/.icons
	ln -fs `realpath ./numix-icon-theme-circle/Numix-Circle` ~/.icons
	ln -fs `realpath ./numix-gtk-theme` ~/.themes
